[package]
name = "pgaibe"
version = "0.1.0"
edition = "2021"


[dependencies]
raylib = { version = "3.7" }
structopt = "0.2"
specs-derive = "0.4.1"
rand = "0.7"
tcod = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arr_macro = "0.1.3"
